-- ============================================================================
-- seed_medicines.sql
--
-- Starting catalogue for public.medicine_catalog.
--
-- This is a STARTING LIST ONLY. It was assembled as a convenience so the
-- prescribing doctor has something to search from on day one. The prescribing
-- doctor is expected to review, correct, extend and prune this list to match
-- personal practice and locally available products.
--
-- Every strength listed here MUST be verified against the current product /
-- current pack before the entry is used in a prescription. Brand names,
-- generic pairings, available strengths and dosage forms change over time and
-- vary between manufacturers and between markets.
--
-- This file contains no dose, frequency, route or duration information of any
-- kind. Strength refers only to the unit strength of the marketed product and
-- is not a recommendation. All prescribing decisions rest with the doctor.
--
-- Safe to re-run: the statement ends with on conflict do nothing.
-- ============================================================================

insert into public.medicine_catalog (name, generic, strength, form, category) values
('Napa','Paracetamol','500 mg','Tablet','Analgesic & Antipyretic'),
('Napa Syrup','Paracetamol','120 mg/5 ml','Syrup','Analgesic & Antipyretic'),
('Napa Suppository','Paracetamol','125 mg','Suppository','Analgesic & Antipyretic'),
('Ace','Paracetamol','500 mg','Tablet','Analgesic & Antipyretic'),
('Xpa','Paracetamol','1 g/100 ml','Injection','Analgesic & Antipyretic'),
('Tramacet','Tramadol Hydrochloride + Paracetamol','37.5 mg + 325 mg','Tablet','Analgesic & Antipyretic'),
('Traxol','Tramadol Hydrochloride','50 mg/ml','Injection','Analgesic & Antipyretic'),
('Nalbun','Nalbuphine Hydrochloride','10 mg/ml','Injection','Analgesic & Antipyretic'),
('Clofenac','Diclofenac Sodium','50 mg','Tablet','NSAID'),
('Clofenac','Diclofenac Sodium','100 mg','Suppository','NSAID'),
('Diclofen Gel','Diclofenac Diethylamine','1%','Gel','NSAID'),
('Flamex','Ibuprofen','400 mg','Tablet','NSAID'),
('Profen','Ibuprofen','100 mg/5 ml','Suspension','NSAID'),
('Naprox','Naproxen','500 mg','Tablet','NSAID'),
('Acenac','Aceclofenac','100 mg','Tablet','NSAID'),
('Rolac','Ketorolac Tromethamine','30 mg/ml','Injection','NSAID'),
('Torix','Etoricoxib','90 mg','Tablet','NSAID'),
('Moxacil','Amoxicillin','500 mg','Capsule','Antibiotic'),
('Fimoxyl','Amoxicillin','125 mg/5 ml','Suspension','Antibiotic'),
('Moxaclav','Amoxicillin + Clavulanic Acid','500 mg + 125 mg','Tablet','Antibiotic'),
('Moxaclav IV','Amoxicillin + Clavulanic Acid','1 g + 200 mg','Injection','Antibiotic'),
('Velosef','Cephradine','500 mg','Capsule','Antibiotic'),
('Cef-3','Cefixime','400 mg','Capsule','Antibiotic'),
('Cef-3','Cefixime','100 mg/5 ml','Suspension','Antibiotic'),
('Sefurox','Cefuroxime Axetil','500 mg','Tablet','Antibiotic'),
('Sefurox IV','Cefuroxime Sodium','750 mg','Injection','Antibiotic'),
('Ceftron','Ceftriaxone Sodium','1 g','Injection','Antibiotic'),
('Ceftazid','Ceftazidime','1 g','Injection','Antibiotic'),
('Cefazol','Cefazolin Sodium','1 g','Injection','Antibiotic'),
('Ciprocin','Ciprofloxacin','500 mg','Tablet','Antibiotic'),
('Ciprocin IV','Ciprofloxacin','200 mg/100 ml','Injection','Antibiotic'),
('Levoxin','Levofloxacin','500 mg','Tablet','Antibiotic'),
('Azin','Azithromycin','500 mg','Tablet','Antibiotic'),
('Klaricid','Clarithromycin','500 mg','Tablet','Antibiotic'),
('Doxicap','Doxycycline Hyclate','100 mg','Capsule','Antibiotic'),
('Amodis','Metronidazole','400 mg','Tablet','Antibiotic'),
('Filmet IV','Metronidazole','500 mg/100 ml','Injection','Antibiotic'),
('Clindacin','Clindamycin Hydrochloride','300 mg','Capsule','Antibiotic'),
('Genacyn','Gentamicin Sulphate','80 mg/2 ml','Injection','Antibiotic'),
('Meropen','Meropenem','1 g','Injection','Antibiotic'),
('Tazopen','Piperacillin + Tazobactam','4 g + 0.5 g','Injection','Antibiotic'),
('Cotrim','Sulphamethoxazole + Trimethoprim','800 mg + 160 mg','Tablet','Antibiotic'),
('Nitrofur','Nitrofurantoin','100 mg','Capsule','Antibiotic'),
('Flugal','Fluconazole','150 mg','Capsule','Antifungal'),
('Itranox','Itraconazole','100 mg','Capsule','Antifungal'),
('Terbin','Terbinafine Hydrochloride','250 mg','Tablet','Antifungal'),
('Terbin','Terbinafine Hydrochloride','1%','Cream','Antifungal'),
('Fungidal','Clotrimazole','1%','Cream','Antifungal'),
('Fungidal HC','Clotrimazole + Hydrocortisone Acetate','1% + 1%','Cream','Antifungal'),
('Xovir','Aciclovir','400 mg','Tablet','Antiviral'),
('Xovir','Aciclovir','5%','Cream','Antiviral'),
('Tenof','Tenofovir Disoproxil Fumarate','300 mg','Tablet','Antiviral'),
('Tinidin','Tinidazole','500 mg','Tablet','Antiprotozoal & Anthelmintic'),
('Secnil','Secnidazole','1 g','Tablet','Antiprotozoal & Anthelmintic'),
('Almex','Albendazole','400 mg','Tablet','Antiprotozoal & Anthelmintic'),
('Almex','Albendazole','200 mg/5 ml','Suspension','Antiprotozoal & Anthelmintic'),
('Ermox','Mebendazole','100 mg','Tablet','Antiprotozoal & Anthelmintic'),
('Scabo','Ivermectin','6 mg','Tablet','Antiprotozoal & Anthelmintic'),
('Seclo','Omeprazole','20 mg','Capsule','Antiulcerant'),
('Seclo IV','Omeprazole Sodium','40 mg','Injection','Antiulcerant'),
('Nexum','Esomeprazole','20 mg','Tablet','Antiulcerant'),
('Maxpro','Esomeprazole','20 mg','Capsule','Antiulcerant'),
('Maxpro IV','Esomeprazole Sodium','40 mg','Injection','Antiulcerant'),
('Sergel','Esomeprazole','20 mg','Tablet','Antiulcerant'),
('Pantonix','Pantoprazole Sodium','20 mg','Tablet','Antiulcerant'),
('Rabifix','Rabeprazole Sodium','20 mg','Tablet','Antiulcerant'),
('Famotack','Famotidine','20 mg','Tablet','Antiulcerant'),
('Antacid Plus','Aluminium Hydroxide + Magnesium Hydroxide + Simethicone','200 mg + 200 mg + 20 mg/5 ml','Suspension','Antiulcerant'),
('Sucral','Sucralfate','1 g/10 ml','Suspension','Antiulcerant'),
('Anset','Ondansetron','8 mg','Tablet','Antiemetic'),
('Anset IV','Ondansetron','4 mg/2 ml','Injection','Antiemetic'),
('Omidon','Domperidone','10 mg','Tablet','Antiemetic'),
('Metolon','Metoclopramide Hydrochloride','10 mg/2 ml','Injection','Antiemetic'),
('Avomine','Promethazine Theoclate','25 mg','Tablet','Antiemetic'),
('Vertina','Betahistine Dihydrochloride','8 mg','Tablet','Antiemetic'),
('Avolac','Lactulose','3.35 g/5 ml','Syrup','Laxative & Anorectal'),
('Fibrogel','Ispaghula Husk','3.5 g','Sachet','Laxative & Anorectal'),
('Dulcolax','Bisacodyl','5 mg','Tablet','Laxative & Anorectal'),
('Dulcolax','Bisacodyl','10 mg','Suppository','Laxative & Anorectal'),
('Glycerin Suppository','Glycerol','2 g','Suppository','Laxative & Anorectal'),
('Enemax','Sodium Acid Phosphate + Sodium Phosphate','16 g + 6 g/100 ml','Solution','Laxative & Anorectal'),
('Peglec','Polyethylene Glycol 3350 + Electrolytes','137.15 g','Sachet','Laxative & Anorectal'),
('Rectocare','Glyceryl Trinitrate','0.2%','Ointment','Laxative & Anorectal'),
('Anodil','Diltiazem Hydrochloride','2%','Ointment','Laxative & Anorectal'),
('Proctosedyl','Cinchocaine Hydrochloride + Hydrocortisone','0.5% + 0.5%','Ointment','Laxative & Anorectal'),
('Daflon','Diosmin + Hesperidin','450 mg + 50 mg','Tablet','Laxative & Anorectal'),
('Venodin','Micronised Purified Flavonoid Fraction (Diosmin + Hesperidin)','500 mg','Tablet','Laxative & Anorectal'),
('Doxium','Calcium Dobesilate','500 mg','Capsule','Laxative & Anorectal'),
('Potassium Permanganate','Potassium Permanganate','0.1% w/v','Solution','Laxative & Anorectal'),
('Algin','Hyoscine Butylbromide','10 mg','Tablet','Antispasmodic'),
('Algin IV','Hyoscine Butylbromide','20 mg/ml','Injection','Antispasmodic'),
('Drotin','Drotaverine Hydrochloride','40 mg','Tablet','Antispasmodic'),
('Visceralgine','Tiemonium Methylsulphate','50 mg','Tablet','Antispasmodic'),
('Visceralgine IV','Tiemonium Methylsulphate','5 mg/2 ml','Injection','Antispasmodic'),
('Colomeb','Mebeverine Hydrochloride','135 mg','Tablet','Antispasmodic'),
('Alatrol','Cetirizine Dihydrochloride','10 mg','Tablet','Antihistamine'),
('Alatrol','Cetirizine Dihydrochloride','5 mg/5 ml','Syrup','Antihistamine'),
('Fexo','Fexofenadine Hydrochloride','120 mg','Tablet','Antihistamine'),
('Loratin','Loratadine','10 mg','Tablet','Antihistamine'),
('Histacin','Chlorpheniramine Maleate','4 mg','Tablet','Antihistamine'),
('Monas','Montelukast','10 mg','Tablet','Respiratory'),
('Monas Plus','Montelukast + Levocetirizine','10 mg + 5 mg','Tablet','Respiratory'),
('Sultolin','Salbutamol','100 mcg/puff','Inhaler','Respiratory'),
('Sultolin','Salbutamol','2 mg/5 ml','Syrup','Respiratory'),
('Iprasol','Ipratropium Bromide + Salbutamol','0.5 mg + 2.5 mg/2.5 ml','Solution','Respiratory'),
('Ticamet','Salmeterol + Fluticasone Propionate','25 mcg + 125 mcg/puff','Inhaler','Respiratory'),
('Formonide','Budesonide + Formoterol Fumarate','200 mcg + 6 mcg/puff','Inhaler','Respiratory'),
('Ambrox','Ambroxol Hydrochloride','15 mg/5 ml','Syrup','Respiratory'),
('Antazol','Xylometazoline Hydrochloride','0.1%','Drops','Respiratory'),
('Amdocal','Amlodipine Besylate','5 mg','Tablet','Cardiovascular'),
('Angilock','Losartan Potassium','50 mg','Tablet','Cardiovascular'),
('Olmecar','Olmesartan Medoxomil','20 mg','Tablet','Cardiovascular'),
('Telsar','Telmisartan','40 mg','Tablet','Cardiovascular'),
('Betaloc','Metoprolol Succinate','50 mg','Tablet','Cardiovascular'),
('Atenol','Atenolol','50 mg','Tablet','Cardiovascular'),
('Bisocor','Bisoprolol Fumarate','5 mg','Tablet','Cardiovascular'),
('Carveda','Carvedilol','6.25 mg','Tablet','Cardiovascular'),
('Ramace','Ramipril','5 mg','Tablet','Cardiovascular'),
('Lanoxin','Digoxin','0.25 mg','Tablet','Cardiovascular'),
('Isordil','Isosorbide Dinitrate','10 mg','Tablet','Cardiovascular'),
('Comet','Metformin Hydrochloride','500 mg','Tablet','Antidiabetic'),
('Secrin','Glimepiride','2 mg','Tablet','Antidiabetic'),
('Diamicron MR','Gliclazide','60 mg','Tablet','Antidiabetic'),
('Sitagen','Sitagliptin','50 mg','Tablet','Antidiabetic'),
('Trajenta','Linagliptin','5 mg','Tablet','Antidiabetic'),
('Jardiance','Empagliflozin','10 mg','Tablet','Antidiabetic'),
('Humulin 70/30','Human Insulin (Isophane + Soluble)','100 IU/ml','Injection','Antidiabetic'),
('Novorapid','Insulin Aspart','100 IU/ml','Injection','Antidiabetic'),
('Atova','Atorvastatin Calcium','10 mg','Tablet','Lipid Lowering'),
('Rosuva','Rosuvastatin Calcium','10 mg','Tablet','Lipid Lowering'),
('Fenolip','Fenofibrate','160 mg','Tablet','Lipid Lowering'),
('Lasix','Furosemide','40 mg','Tablet','Diuretic'),
('Lasix IV','Furosemide','20 mg/2 ml','Injection','Diuretic'),
('Aldactone','Spironolactone','25 mg','Tablet','Diuretic'),
('Lasilactone','Furosemide + Spironolactone','20 mg + 50 mg','Tablet','Diuretic'),
('Cortan','Prednisolone','5 mg','Tablet','Corticosteroid'),
('Oradexon','Dexamethasone','0.5 mg','Tablet','Corticosteroid'),
('Decason','Dexamethasone Sodium Phosphate','5 mg/ml','Injection','Corticosteroid'),
('Hydrocort','Hydrocortisone Sodium Succinate','100 mg','Injection','Corticosteroid'),
('Predmet','Methylprednisolone','4 mg','Tablet','Corticosteroid'),
('Betameson','Betamethasone Valerate','0.1%','Cream','Corticosteroid'),
('Ceevit','Ascorbic Acid','250 mg','Tablet','Vitamin & Mineral'),
('Calbo-D','Calcium Carbonate + Cholecalciferol','500 mg + 200 IU','Tablet','Vitamin & Mineral'),
('D-Rise','Cholecalciferol','40000 IU','Capsule','Vitamin & Mineral'),
('Neurobion','Vitamin B1 + B6 + B12','100 mg + 200 mg + 200 mcg','Tablet','Vitamin & Mineral'),
('Neurobion IV','Vitamin B1 + B6 + B12','100 mg + 100 mg + 1000 mcg/3 ml','Injection','Vitamin & Mineral'),
('Folison','Folic Acid','5 mg','Tablet','Vitamin & Mineral'),
('Methycobal','Mecobalamin','500 mcg','Tablet','Vitamin & Mineral'),
('Baby Zinc','Zinc Sulphate Monohydrate','20 mg/5 ml','Syrup','Vitamin & Mineral'),
('Zeefol','Ferrous Fumarate + Folic Acid','200 mg + 0.4 mg','Capsule','Haematinic'),
('Feronia','Carbonyl Iron + Folic Acid + Zinc Sulphate','50 mg + 0.5 mg + 22.5 mg','Tablet','Haematinic'),
('Venofer','Iron Sucrose','100 mg/5 ml','Injection','Haematinic'),
('Povisep','Povidone Iodine','10%','Solution','Topical & Wound Care'),
('Povisep','Povidone Iodine','5%','Ointment','Topical & Wound Care'),
('Hexisol','Chlorhexidine Gluconate + Isopropyl Alcohol','0.5% + 70%','Solution','Topical & Wound Care'),
('Savlon','Chlorhexidine Gluconate + Cetrimide','0.3% + 3%','Solution','Topical & Wound Care'),
('Silcream','Silver Sulphadiazine','1%','Cream','Topical & Wound Care'),
('Fusidin','Fusidic Acid','2%','Cream','Topical & Wound Care'),
('Mupin','Mupirocin','2%','Ointment','Topical & Wound Care'),
('Nebanol','Neomycin Sulphate + Bacitracin Zinc','5 mg + 250 IU/g','Ointment','Topical & Wound Care'),
('Scabex','Permethrin','5%','Cream','Topical & Wound Care'),
('Dermovate','Clobetasol Propionate','0.05%','Cream','Topical & Wound Care'),
('Jasocaine','Lidocaine Hydrochloride','2%','Injection','Local Anaesthetic'),
('Jasocaine with Adrenaline','Lidocaine Hydrochloride + Adrenaline','2% + 1:200000','Injection','Local Anaesthetic'),
('Jasocaine Jelly','Lidocaine Hydrochloride','2%','Gel','Local Anaesthetic'),
('Xylocaine','Lidocaine Hydrochloride','5%','Ointment','Local Anaesthetic'),
('Xylocaine Spray','Lidocaine Hydrochloride','10%','Solution','Local Anaesthetic'),
('Marcaine Heavy','Bupivacaine Hydrochloride in Dextrose','0.5%','Injection','Local Anaesthetic'),
('Emla','Lidocaine + Prilocaine','2.5% + 2.5%','Cream','Local Anaesthetic'),
('Ecosprin','Aspirin','75 mg','Tablet','Anticoagulant & Antiplatelet'),
('Clopid','Clopidogrel Bisulphate','75 mg','Tablet','Anticoagulant & Antiplatelet'),
('Clexane','Enoxaparin Sodium','40 mg/0.4 ml','Injection','Anticoagulant & Antiplatelet'),
('Heparin Sodium','Heparin Sodium','5000 IU/ml','Injection','Anticoagulant & Antiplatelet'),
('Warf','Warfarin Sodium','5 mg','Tablet','Anticoagulant & Antiplatelet'),
('Xarelto','Rivaroxaban','10 mg','Tablet','Anticoagulant & Antiplatelet'),
('Traxyl','Tranexamic Acid','500 mg','Capsule','Anticoagulant & Antiplatelet'),
('Konakion','Phytomenadione','10 mg/ml','Injection','Anticoagulant & Antiplatelet'),
('Tamsulon','Tamsulosin Hydrochloride','0.4 mg','Capsule','Urology'),
('Finast','Finasteride','5 mg','Tablet','Urology'),
('Solifen','Solifenacin Succinate','5 mg','Tablet','Urology'),
('K-Cit','Potassium Citrate','1100 mg/5 ml','Syrup','Urology'),
('Uropyrin','Phenazopyridine Hydrochloride','100 mg','Tablet','Urology'),
('Sedil','Diazepam','5 mg','Tablet','Psychiatry & Neurology'),
('Sedil IV','Diazepam','10 mg/2 ml','Injection','Psychiatry & Neurology'),
('Disopan','Clonazepam','0.5 mg','Tablet','Psychiatry & Neurology'),
('Dormicum','Midazolam','5 mg/ml','Injection','Psychiatry & Neurology'),
('Tryptin','Amitriptyline Hydrochloride','25 mg','Tablet','Psychiatry & Neurology'),
('Gabapin','Gabapentin','300 mg','Capsule','Psychiatry & Neurology'),
('Pregaba','Pregabalin','75 mg','Capsule','Psychiatry & Neurology'),
('Sertral','Sertraline Hydrochloride','50 mg','Tablet','Psychiatry & Neurology'),
('Normal Saline','Sodium Chloride','0.9%','Solution','IV Fluid'),
('Hartsol','Compound Sodium Lactate (Ringer Lactate)','Isotonic','Solution','IV Fluid'),
('Dextrose Aqua','Dextrose Monohydrate','5%','Solution','IV Fluid'),
('DNS','Dextrose + Sodium Chloride','5% + 0.9%','Solution','IV Fluid'),
('Water for Injection','Sterile Water for Injection','10 ml','Solution','IV Fluid'),
('Orsaline-N','Oral Rehydration Salts','20.5 g','Sachet','IV Fluid')
on conflict do nothing;
